name: Deploy Properdocs

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/site.yml"
      - "site/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Properdocs
        run: |
          pip install properdocs mkdocs-material mkdocs-awesome-pages-plugin

      - name: Install Dependencies
        run: |
          pip install cairosvg

      - name: Build OGP
        run: |
          python ./scripts/generate_ogp.py

      - name: Deploy documentation
        run: properdocs gh-deploy --force
        working-directory: site